project:
  type: website
  resources: 
    - CV.pdf

website:
  title: "Tinashe Chingozha"
  twitter-card: 
    creator: "@Chingozha_T"
  navbar:
    background: primary
    right:
      - text: "Home"
        href: index.qmd
      - text: "Papers"
        href: papers
      - text: "Blog"
        href: blog.qmd
      - text: "Musings"
        href: misc.qmd
  page-footer:
    left : Copyright 2024, Tinashe Chingozha
format:
  html: 
    theme: cosmo
    css: styles.css



